[book]
authors = ["peaceiris"]
language = "en"
src = "src"
title = "Alpine-Based Docker Images for mdBook"

[preprocessor.mermaid]
command = "mdbook-mermaid"
optional = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
