[package]
name = "docker-mdbook"
version = "0.1.0"
authors = ["peaceiris <30958501+peaceiris@users.noreply.github.com>"]
edition = "2018"

[dependencies]
mdbook = "0.5.0"
mdbook-mermaid = "0.17.0"
mdbook-toc = "0.15.0"
